### ISSUE TITLE
Force attestation-agent as keyprovider

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/ocicrypt-rs#33]
Currently we have to create encrypted images for CoCo using `attestation-agent` as the keyprovider when we encrypt. This means that we can't really support generic encrypted images like we hope to. If a client already has a set of encrypted images, they won't be able to use them with CoCo because the keyprovider name won't be correct.

Can we add an option to `ocicrypt-rs` that will ignore the keyprovider name and forward all requests to the `attestation-agent`? This might not work if the original keypovider has an encryption scheme that is not supported by the AA.

**Comment by arronwy** [comment]
Hi @fitzthum , yes, current implementation for image encrypt/decrypt by keyprovider will use the same keyprovider name since this info will be part of container image annotations: https://github.com/containers/ocicrypt/blob/main/docs/keyprovider.md 
```
"annotations":
{
    "org.opencontainers.image.enc.keys.provider.provider_name":"xxxx", 
    "org.opencontainers.image.enc.keys.jwe":"xxxx",
    "org.opencontainers.image.enc.pubopts":"xxxx"
}
```
During decryption, `ocicrypt` and `ocicrypt-rs` will try to find the keyprovider through keyprovider name to decrypt the image even we provide the `OCICRYPT_KEYPROVIDER_CONFIG` for the keyprovider we can use.

This is not what we want since it will require the we have same keyprovider name in `OCICRYPT_KEYPROVIDER_CONFIG` during encryption and decryption.

We may have two options: 
1. during encryption stage, don't append the keyprovider name in annotations:
```
"annotations":
{
    "org.opencontainers.image.enc.keys.provider":"xxxx", 
}
```
2. during decryption stage, ignore the keyprovider name in annotations, and when found image encrypted by scheme: "org.opencontainers.image.enc.keys.provider.xxx", use the keyprovider provided by local `OCICRYPT_KEYPROVIDER_CONFIG`

any suggestions? @pravinrajr9 @lumjjb @sameo

**Comment by arronwy** [comment]
> What about extending ocicrypt-rs to allow wildcard entries in the ocicrypt config file. Then in the guest we could use a config like this to force every request to the AA
> 
> ```
>    {
>         "key-providers": {
>             "*": {
>                 "grpc": "localhost:50051"
>             }
>         }
>     }
> ```

Hi @fitzthum , after we ignore the keyprovider name in container image annotations and use the ocicrypt config file provided by `kata-agent` : https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/src/image_rpc.rs#L185 it will send the request to the right keyprovider service like `attestation-agent`

**Comment by fitzthum** [comment]
@arronwy yeah your PR is functionally equivalent. I just thought it might be nice to stick closer to the existing config file format. Rather than adding a new entry we would allow wildcards. I think either way is fine, though.
